replicaCount: 1
namespace: app1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.20"
service:
  type: ClusterIP
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
