apiVersion: v1
kind: ConfigMap
metadata:
 name: https-cm
 namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
     <head>
      <title>Configmap HTTPS test page</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
     </head>
     <body>
      <h1>Configmap HTTPS test page</h1>
     </body>
    </html>