apiVersion: v1
kind: Pod
metadata:
  labels:
    app: net-deploy
  name: net-deploy
  namespace: default
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 8080