apiVersion: v1
kind: Service
metadata:
  name: net-deploy-svc
  namespace: default
spec:
  selector:
    app: net-deploy
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
  type: ClusterIP