apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deploy
  labels:
    app: net-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: net-deploy
  template:
    metadata:
      labels:
        app: net-deploy
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        imagePullPolicy: IfNotPresent
      - image: wbitt/network-multitool
        name: multitool
        imagePullPolicy: IfNotPresent
        env:
          - name: HTTP_PORT
            value: '8080'
          - name: HTTPS_PORT
            value: '8081'