apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        imagePullPolicy: IfNotPresent
      - image: wbitt/network-multitool
        name: multitool
        imagePullPolicy: IfNotPresent
        env:
          - name: HTTP_PORT
            value: '8080'
          - name: HTTPS_PORT
            value: '8081'
