apiVersion: v1
kind: Service
metadata:
  name: app-deploy-svc
  namespace: default
spec:
  selector:
    app: app-deploy
  ports:
  - name: nginx
    port: 80
  - name: multitool
    port: 8080
  type: ClusterIP