apiVersion: 1
notifiers:
  - name: devops
    type: email
    uid: 22
    org_name: dimilink
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      addresses: "pochta@dimi.link"
