apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deploy
  labels:
    app: nfs-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-deploy
  template:
    metadata:
      labels:
        app: nfs-deploy
    spec:
      containers:
      - image: wbitt/network-multitool
        name: multitool
        volumeMounts:
          - mountPath: /multitool
            name: nfs-volume
        imagePullPolicy: IfNotPresent
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc