apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-deploy
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /k8s_volume/pv_pvc
  persistentVolumeReclaimPolicy: Retain