apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deploy
  namespace: default
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi