apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-deploy
  namespace: default
  labels:
    k8s-app: daemon-deploy
spec:
  selector:
    matchLabels:
      name: daemon-deploy
  template:
    metadata:
      labels:
        name: daemon-deploy
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /multitool
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log