apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unit-rb
  namespace: default
subjects:
  - kind: User
    name: unit
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: unit-role
  apiGroup: rbac.authorization.k8s.io