apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unit-role
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log", "pods/describe" ]
    verbs: [ "list", "gets", "watch" ]